/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**listenInterExample.tlt
*********************************************************************/
#include <vl/exerciseConn.h>
#include <vlutil/vlProcessControl.h>
#include <vlutil/vlKeyboard.h>
#include <vl/exerciseConnInitializer.h>
 
#include "logInInfoInterHLA.h"
 
#include <iostream>
 

 
int keybrdTick(void);
 
// Define a callback to process LogInInfoInter interactions.
void simpleCallback(DtLogInInfoInter* inter, void* /*usr*/)
{
   std::cout << "Received LogInInfoInter Interaction." << std::endl;
   std::cout << *inter << std::endl;
}
 
int main(int argc, char** argv)
{
   try
   {
     
      // Create an exercise conn initializer. This will parse the comand 
      // line, as well as parse an mtl file with the same name as this application.
      DtVrlApplicationInitializer appInit(argc, argv, "VR-Link Listen");
#ifdef DtHLA
     // This creates an empty FOM mapper.  This is not necessary, but without this default VR-Link federates map to RPR so warnings
     // appear if a federate is not RPR based.
      DtFomMapper* emptyMapper = new DtEmptyFomMapper(); 
      appInit.setFomMapper(emptyMapper);
      appInit.setFedFileName("<!FedFileName!>");
#endif
      appInit.parseCmdLine();
      DtExerciseConn exConn(appInit);
 
      // Register a callback to handle fire interactions.
      DtLogInInfoInter::addCallback(&exConn, simpleCallback, NULL);
 
      // Initialize VR-Link time.
      DtClock* clock = exConn.clock();
 
      int forever = 1;
      while (forever)
      {
         // Check if user hit 'q' to quit.
         if (keybrdTick() == -1)
            break;
 
         // Tell VR-Link the current value of simulation time.
         clock->setSimTime(clock->elapsedRealTime());
 
         // Process any incoming messages.
         exConn.drainInput();
 
         // Sleep till next iteration.
         DtSleep(0.1);
      }
   }
   DtCATCH_AND_WARN(std::cout);
   return 0;
}
 
int keybrdTick()
{
   char *keyPtr = DtPollBlockingInputLine();
   if (keyPtr && (*keyPtr == 'q' || *keyPtr == 'Q'))
   {
      return -1;
   }
   return 0;
}
