/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**talkInterExample.tlt
*********************************************************************/
#include <vl/exerciseConnInitializer.h>
#include <vl/exerciseConn.h>
 
#include <vlutil/vlProcessControl.h>
#include <vlutil/vlKeyboard.h>
 
#include "powerCtrlInterHLA.h"
 
 

 
int main(int argc, char** argv)
{
   try
   {
      // Create a connection to the exercise or federation execution.
      DtVrlApplicationInitializer appInit(argc, argv, "VR-Link Talk");
#ifdef DtHLA
     // This creates an empty FOM mapper.  This is not necessary, but without this default VR-Link federates map to RPR so warnings
     // appear if a federate is not RPR based.
      DtFomMapper* emptyMapper = new DtEmptyFomMapper(); 
      appInit.setFomMapper(emptyMapper);
      appInit.setFedFileName("<!FedFileName!>");
#endif
      appInit.parseCmdLine();
      DtExerciseConn exConn(appInit);
 
      // Initialize VR-Link time.
      DtClock* clock = exConn.clock();
 
      // Send a PowerCtrlInter Interaction.
      DtPowerCtrlInter inter;
 
 
      // Here we set some example attribute values.
      // The header files should be consulted for a more
      // complete example.
          
 
      exConn.sendStamped(inter);
 
      // Main loop
      int sendCounter = 0;
      DtTime dt = 0.05;
      DtTime simTime = 0;
      while (simTime <= 10.0)
      {
         // Tell VR-Link the current value of simulation time.
         clock->setSimTime(simTime);
 
         // Process any incoming messages.
         exConn.drainInput();
 
         if ((++sendCounter % 25) == 0)
         {
            exConn.sendStamped(inter);
         }
 
         simTime     += dt;
 
         // Wait till real time equals simulation time of next step.
         DtSleep(simTime - clock->elapsedRealTime()); 
      }
   }
   DtCATCH_AND_WARN(std::cout);
   return 0;
}
