/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**dllExport.tlt
*********************************************************************/
 
#pragma once
 
#ifdef WIN32
#  ifndef DT_DSTACCESSORY_STATIC
#     ifdef DSTACCESSORY_EXPORTS
#        define DT_DLL_DSTACCESSORY __declspec ( dllexport )
#     else
#        define DT_DLL_DSTACCESSORY __declspec ( dllimport )
#     endif
#  else
#     define DT_DLL_DSTACCESSORY
#  endif
#else
#  define DT_DLL_DSTACCESSORY
#endif
