/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintEncSource.tlt
*********************************************************************/
 
#if DtHLA 
 
#include "logInInfoInterEncoderHLA.h"
#include "logInInfoInterHLA.h"
#include <vl/exerciseConnHLA.h>
#include <vlutil/vlStringUtil.h>
#include <vlutil/vlLETypes.h>
#include "DataTypes/udeivceIDnsigned__short.h"
#include "DataTypes/byte__array__10.h"
#include "DataTypes/byte__array.h"

DtLogInInfoInterEncoder::DtLogInInfoInterEncoder(DtExerciseConn* exConn,
   DtInterClassDesc* classDesc) : 
   DtInteractionEncoder(exConn, classDesc)
{
   addEncoder((char*)"publisherType",
      (DtParameterEncoder) encodePublisherType);
   addEncoder((char*)"deviceID",
      (DtParameterEncoder) encodeDeviceID);
   addEncoder((char*)"serviceNumber",
      (DtParameterEncoder) encodeServiceNumber);
   addEncoder((char*)"logInName",
      (DtParameterEncoder) encodeLogInName);
   addEncoder((char*)"affiliation",
      (DtParameterEncoder) encodeAffiliation);

}
 
DtLogInInfoInterEncoder::~DtLogInInfoInterEncoder()
{
}
 
DtLogInInfoInterEncoder::DtLogInInfoInterEncoder(const DtLogInInfoInterEncoder& orig) :
   DtInteractionEncoder(orig)
{
}
 
DtLogInInfoInterEncoder& DtLogInInfoInterEncoder::operator=(const DtLogInInfoInterEncoder& orig)
{
   // Guard against assignment to yourself.
   if (this == &orig)
   {
      return *this;
   }
 
   DtInteractionEncoder::operator=(orig);
 
   return *this;
}
 

void DtLogInInfoInterEncoder::encodePublisherType(const DtLogInInfoInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   DtNetU16 netVal;
   netVal = inter.publisherType();
   params->add(paramHandle, (char*) &netVal, sizeof(DtNetU16));
}

void DtLogInInfoInterEncoder::encodeDeviceID(const DtLogInInfoInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   udeivceIDnsigned__short netVal;
   netVal = inter.deviceID();
   char* buffer = new char[netVal.netSize()];
   netVal.writeToBuffer(buffer);
   params->add(paramHandle,buffer,netVal.netSize());
   delete [] buffer; 
}

void DtLogInInfoInterEncoder::encodeServiceNumber(const DtLogInInfoInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   byte__array__10 netVal;
   netVal = inter.serviceNumber();
   char* buffer = new char[netVal.netSize()];
   netVal.writeToBuffer(buffer);
   params->add(paramHandle,buffer,netVal.netSize());
   delete [] buffer; 
}

void DtLogInInfoInterEncoder::encodeLogInName(const DtLogInInfoInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   byte__array__10 netVal;
   netVal = inter.logInName();
   char* buffer = new char[netVal.netSize()];
   netVal.writeToBuffer(buffer);
   params->add(paramHandle,buffer,netVal.netSize());
   delete [] buffer; 
}

void DtLogInInfoInterEncoder::encodeAffiliation(const DtLogInInfoInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   byte__array netVal;
   netVal = inter.affiliation();
   char* buffer = new char[netVal.netSize()];
   netVal.writeToBuffer(buffer);
   params->add(paramHandle,buffer,netVal.netSize());
   delete [] buffer; 
}

#endif
