/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintEncHeader.tlt
*********************************************************************/
 
//! \file logInInfoInterEncoderHLA.h
//! \brief This file provides a declaration of the class
//! DtLogInInfoInterEncoder.
 
#pragma once
 
#if DtHLA 
 
#include <vl/interactionEncoder.h>
#include "dllExport.h"
 

 
class DtLogInInfoInter;
 
//! Instances of DtLogInInfoInterEncoder are used to encode
//! data from DtLogInInfoInter objects into
//! network structures.
//! \ingroup dstAccessory
class DT_DLL_DSTACCESSORY DtLogInInfoInterEncoder : public DtInteractionEncoder
{
public:
   //! Constructor.
   DtLogInInfoInterEncoder(DtExerciseConn* exConn,
      DtInterClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtLogInInfoInterEncoder();
 
   //! Copy constructor.
   DtLogInInfoInterEncoder(const DtLogInInfoInterEncoder& orig);
 
   //! Assignment operator.
   DtLogInInfoInterEncoder& operator=(const DtLogInInfoInterEncoder& orig);
 
protected:

   //! Encodes PublisherType from inter into params.
   static void encodePublisherType(
      const DtLogInInfoInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

   //! Encodes DeviceID from inter into params.
   static void encodeDeviceID(
      const DtLogInInfoInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

   //! Encodes ServiceNumber from inter into params.
   static void encodeServiceNumber(
      const DtLogInInfoInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

   //! Encodes LogInName from inter into params.
   static void encodeLogInName(
      const DtLogInInfoInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

   //! Encodes Affiliation from inter into params.
   static void encodeAffiliation(
      const DtLogInInfoInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

};
 

 
#endif
