/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintDecSource.tlt
*********************************************************************/
 
#if DtHLA 
 
#include "logInInfoInterDecoderHLA.h"
#include "logInInfoInterHLA.h"
#include <vl/exerciseConnHLA.h>
#include <vlutil/vlStringUtil.h>
#include <vlutil/vlLETypes.h>
#include <vector>
#include "DataTypes/udeivceIDnsigned__short.h"
#include "DataTypes/byte__array__10.h"
#include "DataTypes/byte__array.h"

DtLogInInfoInterDecoder::DtLogInInfoInterDecoder(
   DtExerciseConn* exConn,
   DtInterClassDesc* classDesc) : 
   DtInteractionDecoder(exConn, classDesc)
{
   addDecoder((char*)"publisherType",
      (DtParameterDecoder) decodePublisherType);
   addDecoder((char*)"deviceID",
      (DtParameterDecoder) decodeDeviceID);
   addDecoder((char*)"serviceNumber",
      (DtParameterDecoder) decodeServiceNumber);
   addDecoder((char*)"logInName",
      (DtParameterDecoder) decodeLogInName);
   addDecoder((char*)"affiliation",
      (DtParameterDecoder) decodeAffiliation);

}
 
DtLogInInfoInterDecoder::~DtLogInInfoInterDecoder()
{
}
 
DtLogInInfoInterDecoder::DtLogInInfoInterDecoder(const DtLogInInfoInterDecoder& orig) :
   DtInteractionDecoder(orig)
{
}
 
DtLogInInfoInterDecoder& DtLogInInfoInterDecoder::operator=(const DtLogInInfoInterDecoder& orig)
{
   // Guard against assignment to yourself.
   if (this == &orig)
   {
      return *this;
   }
 
   DtInteractionDecoder::operator=(orig);
 
   return *this;
}
 

void DtLogInInfoInterDecoder::decodePublisherType(
   DtLogInInfoInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   DtNetU16 netVal;
   params.getValue(pairSetIndex, (char*)&netVal, length);
   inter->setPublisherType(netVal);
}

void DtLogInInfoInterDecoder::decodeDeviceID(
   DtLogInInfoInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   char* buffer = new char[length];
   params.getValue(pairSetIndex, buffer, length);
   udeivceIDnsigned__short netVal;
   netVal.fillFromBuffer(buffer, length, 0);
   DtDELETE(buffer);
   inter->setDeviceID(netVal);
}

void DtLogInInfoInterDecoder::decodeServiceNumber(
   DtLogInInfoInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   char* buffer = new char[length];
   params.getValue(pairSetIndex, buffer, length);
   byte__array__10 netVal;
   netVal.fillFromBuffer(buffer, length, 0);
   DtDELETE(buffer);
   inter->setServiceNumber(netVal);
}

void DtLogInInfoInterDecoder::decodeLogInName(
   DtLogInInfoInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   char* buffer = new char[length];
   params.getValue(pairSetIndex, buffer, length);
   byte__array__10 netVal;
   netVal.fillFromBuffer(buffer, length, 0);
   DtDELETE(buffer);
   inter->setLogInName(netVal);
}

void DtLogInInfoInterDecoder::decodeAffiliation(
   DtLogInInfoInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   char* buffer = new char[length];
   params.getValue(pairSetIndex, buffer, length);
   byte__array netVal;
   netVal.fillFromBuffer(buffer, length, 0);
   DtDELETE(buffer);
   inter->setAffiliation(netVal);
}

#endif
