/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintDecHeader.tlt
*********************************************************************/
 
//! \file logInInfoInterDecoderHLA.h
//! \brief Contains the DtLogInInfoInterDecoder class declaration.
//! \ingroup dstAccessory
 
#pragma once
 
#if DtHLA 
 
#include <vl/interactionDecoder.h>
#include "dllExport.h"
 

 
class DtLogInInfoInter;
 
//! Instances of DtLogInInfoInterDecoder are used to decode
//! data from the network into DtLogInInfoInter
//! objects.
//! \ingroup dstAccessory
class DT_DLL_DSTACCESSORY DtLogInInfoInterDecoder : public DtInteractionDecoder
{
public:
   //! Constructor.
   DtLogInInfoInterDecoder(DtExerciseConn* exConn,
      DtInterClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtLogInInfoInterDecoder();
 
   //! Copy constructor.
   DtLogInInfoInterDecoder(const DtLogInInfoInterDecoder& orig);
 
   //! Assignment operator.
   DtLogInInfoInterDecoder& operator=(const DtLogInInfoInterDecoder& orig);
 
protected:

   //! Decodes PublisherType from params into inter.
   static void decodePublisherType(
      DtLogInInfoInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes DeviceID from params into inter.
   static void decodeDeviceID(
      DtLogInInfoInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes ServiceNumber from params into inter.
   static void decodeServiceNumber(
      DtLogInInfoInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes LogInName from params into inter.
   static void decodeLogInName(
      DtLogInInfoInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes Affiliation from params into inter.
   static void decodeAffiliation(
      DtLogInInfoInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

};
 

 
#endif
