/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hinterSource.tlt
*********************************************************************/
 
#if DtHLA 
 
#include "logInInfoInterHLA.h"
#include <vlutil/vlPrintUtil.h>
#include <vl/exerciseConn.h>
#include <vl/interactionFactory.h>
#include "logInInfoInterEncoderHLA.h"
#include "logInInfoInterDecoderHLA.h"
 

 
DtLogInInfoInter::DtLogInInfoInter() :
   DtInteractionWithEncDec(),
   myPublisherType(0),
   myDeviceID(),
   myServiceNumber(),
   myLogInName(),
   myAffiliation()
{
}
 
DtLogInInfoInter::~DtLogInInfoInter()
{
}
 
DtLogInInfoInter::DtLogInInfoInter(
   const DtLogInInfoInter& orig) :
   DtInteractionWithEncDec(orig),
   myPublisherType(orig.myPublisherType),
   myDeviceID(orig.myDeviceID),
   myServiceNumber(orig.myServiceNumber),
   myLogInName(orig.myLogInName),
   myAffiliation(orig.myAffiliation)
{   
}
 
DtLogInInfoInter& DtLogInInfoInter::operator=(
   const DtLogInInfoInter& orig)
{
   // Guard against assignment to yourself.
   if (this == &orig)
   {
      return *this;
   }
 
   DtInteractionWithEncDec::operator=(orig);
   myPublisherType = orig.myPublisherType;
   myDeviceID = orig.myDeviceID;
   myServiceNumber = orig.myServiceNumber;
   myLogInName = orig.myLogInName;
   myAffiliation = orig.myAffiliation;

 
   return *this;
}
 
DtInteraction* DtLogInInfoInter::create()
{
   return new DtLogInInfoInter();
}
 
void DtLogInInfoInter::printData() const
{
   printDataToStream(DtInfo);
}
 
void DtLogInInfoInter::printDataToStream(std::ostream& stream) const
{
   DtPrintAttribute(stream, "PublisherType", myPublisherType);
   stream << "DeviceID: \n";
   for(unsigned int index = 0; index < myDeviceID.size(); ++index)
   {
      DtPrintAttribute(stream, "DeviceID", myDeviceID[index]);
   }

   stream << "ServiceNumber: \n";
   for(unsigned int index = 0; index < myServiceNumber.size(); ++index)
   {
      DtPrintAttribute(stream, "ServiceNumber", myServiceNumber[index]);
   }

   stream << "LogInName: \n";
   for(unsigned int index = 0; index < myLogInName.size(); ++index)
   {
      DtPrintAttribute(stream, "LogInName", myLogInName[index]);
   }

   stream << "Affiliation: \n";
   for(unsigned int index = 0; index < myAffiliation.size(); ++index)
   {
      DtPrintAttribute(stream, "Affiliation", myAffiliation[index]);
   }

}
 
void DtLogInInfoInter::addCallback(DtExerciseConn* conn,
   DtLogInInfoInterCb cb, void* usr, DtDDMRegionSP region)
{
   conn->addInteractionCallbackByName("LogInInfo",
      (DtReceiveInteractionCb) cb, usr, region);
      
   conn->interactionFactory()->addCreator("LogInInfo",
      DtLogInInfoInter::create);
}
 
void DtLogInInfoInter::removeCallback(DtExerciseConn* conn,
   DtLogInInfoInterCb cb, void* usr, DtDDMRegionSP region)
{
   conn->removeInteractionCallbackByName("LogInInfo",
      (DtReceiveInteractionCb) cb, usr, region);
}

void DtLogInInfoInter::setPublisherType(DtU16 val)
{
   myPublisherType = val;
}
 
DtU16 DtLogInInfoInter::publisherType() const
{
   return myPublisherType;
}
 


void DtLogInInfoInter::setDeviceID(const udeivceIDnsigned__short& val)
{
   myDeviceID = val;
}
 
const udeivceIDnsigned__short& DtLogInInfoInter::deviceID() const
{
   return myDeviceID;
}
 


void DtLogInInfoInter::setServiceNumber(const byte__array__10& val)
{
   myServiceNumber = val;
}
 
const byte__array__10& DtLogInInfoInter::serviceNumber() const
{
   return myServiceNumber;
}
 


void DtLogInInfoInter::setLogInName(const byte__array__10& val)
{
   myLogInName = val;
}
 
const byte__array__10& DtLogInInfoInter::logInName() const
{
   return myLogInName;
}
 


void DtLogInInfoInter::setAffiliation(const byte__array& val)
{
   myAffiliation = val;
}
 
const byte__array& DtLogInInfoInter::affiliation() const
{
   return myAffiliation;
}
 


 
const char* DtLogInInfoInter::interactionClassToUse(DtExerciseConn* exConn) const
{
  return "LogInInfo";
}
 
DtInteractionDecoder* DtLogInInfoInter::createDecoder(
   DtExerciseConn* exConn) const
{
   return new DtLogInInfoInterDecoder(exConn, classDesc());
}
 
DtInteractionEncoder* DtLogInInfoInter::createEncoder(
   DtExerciseConn* exConn) const
{
   return new DtLogInInfoInterEncoder(exConn, classDesc());
}
 

 
#endif
