/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hinterHeader.tlt
*********************************************************************/
 
//! \file logInInfoInterHLA.h
//! \brief Contains the DtLogInInfoInter class declaration.
//! \ingroup dstAccessory
 
#pragma once
 
#if DtHLA 
 
#include "dllExport.h"
#include <vl/interactionWithEncDec.h>
#include "DataTypes/dstAccessoryEnums.h"
#include <vlutil/vlString.h>
#include <vl/globalObjectDesignator.h>
#include <vl/hlaLogicalTime.h>
#include <vl/hlaLogicalTimeInterval.h>
#include <vlpi/entityType.h>
#include <vlpi/entityIdentifier.h>
#include <matrix/vlVector.h>
 
#include "DataTypes/udeivceIDnsigned__short.h"
#include "DataTypes/byte__array__10.h"
#include "DataTypes/byte__array.h"
 
class DtExerciseConn;
 
 
class DtLogInInfoInter;
 
//! DtLogInInfoInter  callback function signature.
typedef void (*DtLogInInfoInterCb) (DtLogInInfoInter* inter, 
   void* usr);
 
//! Instances of DtLogInInfoInter are used to store state data for
//! LogInInfo interactions.
//! \ingroup dstAccessory
class DT_DLL_DSTACCESSORY DtLogInInfoInter : public DtInteractionWithEncDec
{
public:
 
   //! Constructor.
   DtLogInInfoInter();
 
   //! Destructor.
   virtual ~DtLogInInfoInter();
 
   //! Copy constructor.
   DtLogInInfoInter(const DtLogInInfoInter& orig);
 
   //! Assignment operator.
   DtLogInInfoInter& operator=(const DtLogInInfoInter& orig);
 
   //! Print the interaction's data.
   virtual void printData() const;
 
   //! Print the interaction's data to the specified stream
   virtual void printDataToStream(std::ostream& stream) const;
   

   //! PublisherType mutator.
   virtual void setPublisherType(DtU16 val);
 
   //! PublisherType accessor.
   virtual DtU16 publisherType() const;
 


   //! DeviceID mutator.
   virtual void setDeviceID(const udeivceIDnsigned__short& val);
 
   //! DeviceID accessor.
   virtual const udeivceIDnsigned__short& deviceID() const;
 


   //! ServiceNumber mutator.
   virtual void setServiceNumber(const byte__array__10& val);
 
   //! ServiceNumber accessor.
   virtual const byte__array__10& serviceNumber() const;
 


   //! LogInName mutator.
   virtual void setLogInName(const byte__array__10& val);
 
   //! LogInName accessor.
   virtual const byte__array__10& logInName() const;
 


   //! Affiliation mutator.
   virtual void setAffiliation(const byte__array& val);
 
   //! Affiliation accessor.
   virtual const byte__array& affiliation() const;
 


      
   //! Name of the interaction. (Not necessarily the ClassName from the FOM.)
   virtual const char* name() const { return "DtLogInInfoInter"; }
 
public:
 
   //! Create a DtLogInInfoInter.
   //! Caller is responsible for deletion.
   static DtInteraction* create();
 
   //! Add (register)/Remove (deregister) function to be called when
   //! interaction occurs.
   static void addCallback(DtExerciseConn* conn,
      DtLogInInfoInterCb cb, void* usr,
      DtDDMRegionSP region = DtDDMRegionSP());
   static void removeCallback(DtExerciseConn* conn,
      DtLogInInfoInterCb cb, void* usr,
      DtDDMRegionSP region = DtDDMRegionSP());
 
protected:
   virtual const char* interactionClassToUse(DtExerciseConn* exConn) const;
 
   virtual DtInteractionDecoder* createDecoder(DtExerciseConn* exConn) const;
   virtual DtInteractionEncoder* createEncoder(DtExerciseConn* exConn) const;
      
      
protected:
   DtU16 myPublisherType;
   udeivceIDnsigned__short myDeviceID;
   byte__array__10 myServiceNumber;
   byte__array__10 myLogInName;
   byte__array myAffiliation;

};

 
#endif
