/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hinterHeader.tlt
*********************************************************************/
 
//! \file powerCtrlInterHLA.h
//! \brief Contains the DtPowerCtrlInter class declaration.
//! \ingroup dstAccessory
 
#pragma once
 
#if DtHLA 
 
#include "dllExport.h"
#include <vl/interactionWithEncDec.h>
#include "DataTypes/dstAccessoryEnums.h"
#include <vlutil/vlString.h>
#include <vl/globalObjectDesignator.h>
#include <vl/hlaLogicalTime.h>
#include <vl/hlaLogicalTimeInterval.h>
#include <vlpi/entityType.h>
#include <vlpi/entityIdentifier.h>
#include <matrix/vlVector.h>
 
#include "DataTypes/byte.h"
 
class DtExerciseConn;
 
 
class DtPowerCtrlInter;
 
//! DtPowerCtrlInter  callback function signature.
typedef void (*DtPowerCtrlInterCb) (DtPowerCtrlInter* inter, 
   void* usr);
 
//! Instances of DtPowerCtrlInter are used to store state data for
//! PowerCtrl interactions.
//! \ingroup dstAccessory
class DT_DLL_DSTACCESSORY DtPowerCtrlInter : public DtInteractionWithEncDec
{
public:
 
   //! Constructor.
   DtPowerCtrlInter();
 
   //! Destructor.
   virtual ~DtPowerCtrlInter();
 
   //! Copy constructor.
   DtPowerCtrlInter(const DtPowerCtrlInter& orig);
 
   //! Assignment operator.
   DtPowerCtrlInter& operator=(const DtPowerCtrlInter& orig);
 
   //! Print the interaction's data.
   virtual void printData() const;
 
   //! Print the interaction's data to the specified stream
   virtual void printDataToStream(std::ostream& stream) const;
   

   //! PowerCtrlMsg mutator.
   virtual void setPowerCtrlMsg(const byte& val);
 
   //! PowerCtrlMsg accessor.
   virtual const byte& powerCtrlMsg() const;
 


   //! DestinationSystem mutator.
   virtual void setDestinationSystem(const byte& val);
 
   //! DestinationSystem accessor.
   virtual const byte& destinationSystem() const;
 


      
   //! Name of the interaction. (Not necessarily the ClassName from the FOM.)
   virtual const char* name() const { return "DtPowerCtrlInter"; }
 
public:
 
   //! Create a DtPowerCtrlInter.
   //! Caller is responsible for deletion.
   static DtInteraction* create();
 
   //! Add (register)/Remove (deregister) function to be called when
   //! interaction occurs.
   static void addCallback(DtExerciseConn* conn,
      DtPowerCtrlInterCb cb, void* usr,
      DtDDMRegionSP region = DtDDMRegionSP());
   static void removeCallback(DtExerciseConn* conn,
      DtPowerCtrlInterCb cb, void* usr,
      DtDDMRegionSP region = DtDDMRegionSP());
 
protected:
   virtual const char* interactionClassToUse(DtExerciseConn* exConn) const;
 
   virtual DtInteractionDecoder* createDecoder(DtExerciseConn* exConn) const;
   virtual DtInteractionEncoder* createEncoder(DtExerciseConn* exConn) const;
      
      
protected:
   byte myPowerCtrlMsg;
   byte myDestinationSystem;

};

 
#endif
