/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintDecHeader.tlt
*********************************************************************/
 
//! \file powerCtrlInterDecoderHLA.h
//! \brief Contains the DtPowerCtrlInterDecoder class declaration.
//! \ingroup dstAccessory
 
#pragma once
 
#if DtHLA 
 
#include <vl/interactionDecoder.h>
#include "dllExport.h"
 

 
class DtPowerCtrlInter;
 
//! Instances of DtPowerCtrlInterDecoder are used to decode
//! data from the network into DtPowerCtrlInter
//! objects.
//! \ingroup dstAccessory
class DT_DLL_DSTACCESSORY DtPowerCtrlInterDecoder : public DtInteractionDecoder
{
public:
   //! Constructor.
   DtPowerCtrlInterDecoder(DtExerciseConn* exConn,
      DtInterClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtPowerCtrlInterDecoder();
 
   //! Copy constructor.
   DtPowerCtrlInterDecoder(const DtPowerCtrlInterDecoder& orig);
 
   //! Assignment operator.
   DtPowerCtrlInterDecoder& operator=(const DtPowerCtrlInterDecoder& orig);
 
protected:

   //! Decodes PowerCtrlMsg from params into inter.
   static void decodePowerCtrlMsg(
      DtPowerCtrlInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

   //! Decodes DestinationSystem from params into inter.
   static void decodeDestinationSystem(
      DtPowerCtrlInter* inter,
      const RTI::ParameterHandleValuePairSet& params,
      int pairSetIndex);

};
 

 
#endif
