/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hinterSource.tlt
*********************************************************************/
 
#if DtHLA 
 
#include "powerCtrlInterHLA.h"
#include <vlutil/vlPrintUtil.h>
#include <vl/exerciseConn.h>
#include <vl/interactionFactory.h>
#include "powerCtrlInterEncoderHLA.h"
#include "powerCtrlInterDecoderHLA.h"
 

 
DtPowerCtrlInter::DtPowerCtrlInter() :
   DtInteractionWithEncDec(),
   myPowerCtrlMsg(),
   myDestinationSystem()
{
}
 
DtPowerCtrlInter::~DtPowerCtrlInter()
{
}
 
DtPowerCtrlInter::DtPowerCtrlInter(
   const DtPowerCtrlInter& orig) :
   DtInteractionWithEncDec(orig),
   myPowerCtrlMsg(orig.myPowerCtrlMsg),
   myDestinationSystem(orig.myDestinationSystem)
{   
}
 
DtPowerCtrlInter& DtPowerCtrlInter::operator=(
   const DtPowerCtrlInter& orig)
{
   // Guard against assignment to yourself.
   if (this == &orig)
   {
      return *this;
   }
 
   DtInteractionWithEncDec::operator=(orig);
   myPowerCtrlMsg = orig.myPowerCtrlMsg;
   myDestinationSystem = orig.myDestinationSystem;

 
   return *this;
}
 
DtInteraction* DtPowerCtrlInter::create()
{
   return new DtPowerCtrlInter();
}
 
void DtPowerCtrlInter::printData() const
{
   printDataToStream(DtInfo);
}
 
void DtPowerCtrlInter::printDataToStream(std::ostream& stream) const
{
   DtPrintAttribute(stream, "PowerCtrlMsg", myPowerCtrlMsg);
   DtPrintAttribute(stream, "DestinationSystem", myDestinationSystem);
}
 
void DtPowerCtrlInter::addCallback(DtExerciseConn* conn,
   DtPowerCtrlInterCb cb, void* usr, DtDDMRegionSP region)
{
   conn->addInteractionCallbackByName("PowerCtrl",
      (DtReceiveInteractionCb) cb, usr, region);
      
   conn->interactionFactory()->addCreator("PowerCtrl",
      DtPowerCtrlInter::create);
}
 
void DtPowerCtrlInter::removeCallback(DtExerciseConn* conn,
   DtPowerCtrlInterCb cb, void* usr, DtDDMRegionSP region)
{
   conn->removeInteractionCallbackByName("PowerCtrl",
      (DtReceiveInteractionCb) cb, usr, region);
}

void DtPowerCtrlInter::setPowerCtrlMsg(const byte& val)
{
   myPowerCtrlMsg = val;
}
 
const byte& DtPowerCtrlInter::powerCtrlMsg() const
{
   return myPowerCtrlMsg;
}
 


void DtPowerCtrlInter::setDestinationSystem(const byte& val)
{
   myDestinationSystem = val;
}
 
const byte& DtPowerCtrlInter::destinationSystem() const
{
   return myDestinationSystem;
}
 


 
const char* DtPowerCtrlInter::interactionClassToUse(DtExerciseConn* exConn) const
{
  return "PowerCtrl";
}
 
DtInteractionDecoder* DtPowerCtrlInter::createDecoder(
   DtExerciseConn* exConn) const
{
   return new DtPowerCtrlInterDecoder(exConn, classDesc());
}
 
DtInteractionEncoder* DtPowerCtrlInter::createEncoder(
   DtExerciseConn* exConn) const
{
   return new DtPowerCtrlInterEncoder(exConn, classDesc());
}
 

 
#endif
