/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintEncHeader.tlt
*********************************************************************/
 
//! \file powerCtrlInterEncoderHLA.h
//! \brief This file provides a declaration of the class
//! DtPowerCtrlInterEncoder.
 
#pragma once
 
#if DtHLA 
 
#include <vl/interactionEncoder.h>
#include "dllExport.h"
 

 
class DtPowerCtrlInter;
 
//! Instances of DtPowerCtrlInterEncoder are used to encode
//! data from DtPowerCtrlInter objects into
//! network structures.
//! \ingroup dstAccessory
class DT_DLL_DSTACCESSORY DtPowerCtrlInterEncoder : public DtInteractionEncoder
{
public:
   //! Constructor.
   DtPowerCtrlInterEncoder(DtExerciseConn* exConn,
      DtInterClassDesc* classDesc);
 
   //! Destructor.
   virtual ~DtPowerCtrlInterEncoder();
 
   //! Copy constructor.
   DtPowerCtrlInterEncoder(const DtPowerCtrlInterEncoder& orig);
 
   //! Assignment operator.
   DtPowerCtrlInterEncoder& operator=(const DtPowerCtrlInterEncoder& orig);
 
protected:

   //! Encodes PowerCtrlMsg from inter into params.
   static void encodePowerCtrlMsg(
      const DtPowerCtrlInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

   //! Encodes DestinationSystem from inter into params.
   static void encodeDestinationSystem(
      const DtPowerCtrlInter& inter,
      RTI::ParameterHandleValuePairSet* params,
      RTI::ParameterHandle paramHandle);

};
 

 
#endif
