/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintDecSource.tlt
*********************************************************************/
 
#if DtHLA 
 
#include "powerCtrlInterDecoderHLA.h"
#include "powerCtrlInterHLA.h"
#include <vl/exerciseConnHLA.h>
#include <vlutil/vlStringUtil.h>
#include <vlutil/vlLETypes.h>
#include <vector>
#include "DataTypes/byte.h"

DtPowerCtrlInterDecoder::DtPowerCtrlInterDecoder(
   DtExerciseConn* exConn,
   DtInterClassDesc* classDesc) : 
   DtInteractionDecoder(exConn, classDesc)
{
   addDecoder((char*)"powerCtrlMsg",
      (DtParameterDecoder) decodePowerCtrlMsg);
   addDecoder((char*)"destinationSystem",
      (DtParameterDecoder) decodeDestinationSystem);

}
 
DtPowerCtrlInterDecoder::~DtPowerCtrlInterDecoder()
{
}
 
DtPowerCtrlInterDecoder::DtPowerCtrlInterDecoder(const DtPowerCtrlInterDecoder& orig) :
   DtInteractionDecoder(orig)
{
}
 
DtPowerCtrlInterDecoder& DtPowerCtrlInterDecoder::operator=(const DtPowerCtrlInterDecoder& orig)
{
   // Guard against assignment to yourself.
   if (this == &orig)
   {
      return *this;
   }
 
   DtInteractionDecoder::operator=(orig);
 
   return *this;
}
 

void DtPowerCtrlInterDecoder::decodePowerCtrlMsg(
   DtPowerCtrlInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   char* buffer = new char[length];
   params.getValue(pairSetIndex, buffer, length);
   byte netVal;
   netVal.fillFromBuffer(buffer, length, 0);
   DtDELETE(buffer);
   inter->setPowerCtrlMsg(netVal);
}

void DtPowerCtrlInterDecoder::decodeDestinationSystem(
   DtPowerCtrlInter* inter,
   const RTI::ParameterHandleValuePairSet& params,
   int pairSetIndex)
{
   RTI::ULong length = params.getValueLength(pairSetIndex);
   char* buffer = new char[length];
   params.getValue(pairSetIndex, buffer, length);
   byte netVal;
   netVal.fillFromBuffer(buffer, length, 0);
   DtDELETE(buffer);
   inter->setDestinationSystem(netVal);
}

#endif
