/*********************************************************************
**This file was generated by MAK Technologies' VR-Link Code Generator.
**hintEncSource.tlt
*********************************************************************/
 
#if DtHLA 
 
#include "powerCtrlInterEncoderHLA.h"
#include "powerCtrlInterHLA.h"
#include <vl/exerciseConnHLA.h>
#include <vlutil/vlStringUtil.h>
#include <vlutil/vlLETypes.h>
#include "DataTypes/byte.h"

DtPowerCtrlInterEncoder::DtPowerCtrlInterEncoder(DtExerciseConn* exConn,
   DtInterClassDesc* classDesc) : 
   DtInteractionEncoder(exConn, classDesc)
{
   addEncoder((char*)"powerCtrlMsg",
      (DtParameterEncoder) encodePowerCtrlMsg);
   addEncoder((char*)"destinationSystem",
      (DtParameterEncoder) encodeDestinationSystem);

}
 
DtPowerCtrlInterEncoder::~DtPowerCtrlInterEncoder()
{
}
 
DtPowerCtrlInterEncoder::DtPowerCtrlInterEncoder(const DtPowerCtrlInterEncoder& orig) :
   DtInteractionEncoder(orig)
{
}
 
DtPowerCtrlInterEncoder& DtPowerCtrlInterEncoder::operator=(const DtPowerCtrlInterEncoder& orig)
{
   // Guard against assignment to yourself.
   if (this == &orig)
   {
      return *this;
   }
 
   DtInteractionEncoder::operator=(orig);
 
   return *this;
}
 

void DtPowerCtrlInterEncoder::encodePowerCtrlMsg(const DtPowerCtrlInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   byte netVal;
   netVal = inter.powerCtrlMsg();
   char* buffer = new char[netVal.netSize()];
   netVal.writeToBuffer(buffer);
   params->add(paramHandle,buffer,netVal.netSize());
   delete [] buffer; 
}

void DtPowerCtrlInterEncoder::encodeDestinationSystem(const DtPowerCtrlInter& inter,
   RTI::ParameterHandleValuePairSet* params,
   RTI::ParameterHandle paramHandle)
{
   byte netVal;
   netVal = inter.destinationSystem();
   char* buffer = new char[netVal.netSize()];
   netVal.writeToBuffer(buffer);
   params->add(paramHandle,buffer,netVal.netSize());
   delete [] buffer; 
}

#endif
